import * as vscode from 'vscode';
import { CodePilotApiClient } from '../api';
import { CodePilotDiffProvider } from '../providers/diffContentProvider';

export function registerFixCommand(
  context: vscode.ExtensionContext,
  apiClient: CodePilotApiClient,
  diffProvider: CodePilotDiffProvider
) {
  return vscode.commands.registerCommand('codepilot.fixSelectedCode', async () => {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showInformationMessage('CodePilot: Open a file and select code to fix.');
      return;
    }

    const document = editor.document;
    const selection = editor.selection;
    let codeToFix = document.getText(selection);
    const isSelection = Boolean(codeToFix && codeToFix.trim().length > 0);

    if (!isSelection) {
      const choice = await vscode.window.showQuickPick(
        ['Fix Entire Current File', 'Cancel'],
        { placeHolder: 'No code selected. Would you like to fix the entire file?' }
      );
      if (choice === 'Fix Entire Current File') {
        codeToFix = document.getText();
      } else {
        return;
      }
    }

    const language = document.languageId;

    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: 'CodePilot: Synthesizing fixes & optimizations...',
        cancellable: false,
      },
      async () => {
        try {
          const result = await apiClient.fixCode(codeToFix, language);

          if (!result || !result.correctedCode) {
            vscode.window.showErrorMessage('CodePilot: No fix was generated by the backend.');
            return;
          }

          // Build full proposed text for comparison
          let fullProposedText: string;
          let targetRange: vscode.Range;

          if (isSelection) {
            targetRange = selection;
            const fullOriginal = document.getText();
            const startOffset = document.offsetAt(selection.start);
            const endOffset = document.offsetAt(selection.end);
            fullProposedText =
              fullOriginal.substring(0, startOffset) +
              result.correctedCode +
              fullOriginal.substring(endOffset);
          } else {
            targetRange = new vscode.Range(0, 0, document.lineCount, 0);
            fullProposedText = result.correctedCode;
          }

          // Create virtual URI for proposed fix
          const proposedUri = vscode.Uri.parse(
            `${CodePilotDiffProvider.scheme}://proposed-fix/${encodeURIComponent(document.fileName)}`
          );

          diffProvider.setDocumentContent(proposedUri, fullProposedText);

          // Show VS Code side-by-side diff
          const title = `Original ↔ CodePilot Proposed Fix (${document.fileName.split('/').pop()})`;
          await vscode.commands.executeCommand('vscode.diff', document.uri, proposedUri, title);

          // Present Accept / Reject options with summary of fixes
          const summaryPreview = result.summaryOfFixes.slice(0, 2).join('; ');
          const action = await vscode.window.showInformationMessage(
            `CodePilot Fixes: ${summaryPreview}`,
            { modal: false },
            'Accept Fix',
            'Reject Fix'
          );

          if (action === 'Accept Fix') {
            // Apply fix to the actual document
            const edit = new vscode.WorkspaceEdit();
            if (isSelection) {
              edit.replace(document.uri, targetRange, result.correctedCode);
            } else {
              const fullRange = new vscode.Range(
                document.positionAt(0),
                document.positionAt(document.getText().length)
              );
              edit.replace(document.uri, fullRange, result.correctedCode);
            }

            const success = await vscode.workspace.applyEdit(edit);
            if (success) {
              vscode.window.showInformationMessage('CodePilot: Proposed fix successfully applied!');
            }
          } else {
            vscode.window.showInformationMessage('CodePilot: Proposed fix rejected. Original code preserved.');
          }

          // Clean up virtual diff content
          diffProvider.clear(proposedUri);
        } catch (err: any) {
          vscode.window.showErrorMessage(`CodePilot Error: ${err.message || 'Failed to fix code.'}`);
        }
      }
    );
  });
}
